### ISSUE TITLE
Customize invalid Links class and title

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#3]
Implement the ability to specify in `_config.yml`:

- [x] whether to add a class to the invalid link, and specify its name
- [x] wether to add a title to show an on-hover message

<br>
<br>

### Example

```yaml
wikilinks:
  collection: '_notes'
  title: 'This note is private'
  class: 'private'
```

which, in the case of a note called `Private note example` not existing, parses:

```html
<span class="private" title="This note is private"><span>[[</span>Private note example<span>]]</span></span>
```
